# Generated by Django 5.1.7 on 2025-04-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_materia_remove_avaliacao_turma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_avaliacao']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='turmamateria',
            options={'ordering': ['turma__nome']},
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='avaliacao_unica_por_aluno&turma',
        ),
        migrations.RemoveConstraint(
            model_name='turmamateria',
            name='unique_turma&_materia&_professor',
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma_materia'), name='avaliacao_unica_por_aluno_turma'),
        ),
        migrations.AddConstraint(
            model_name='turmamateria',
            constraint=models.UniqueConstraint(fields=('turma', 'materia', 'professor'), name='unique_turma_materia_professor'),
        ),
    ]
