# Generated by Django 5.1.7 on 2025-04-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_avaliacao_options_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turmamateria',
            options={},
        ),
    ]
